version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama

  
  fastapi:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - ollama
    env_file:
      - backend/.env

  streamlit:
    build:
      context: ./streamlit_app
      dockerfile: ../Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://fastapi:8000
    depends_on:
      - fastapi

volumes:
  mongo_data:
  ollama_models:
